[tool.poetry]
name = "abatarapp"
version = "0.1.0"
description = "ABatar streamlit package"
authors = ["Prajwal Kafle <prajwal.kafle@sportsbet.com.au>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.14"
scipy = "^1.15.2"
numpy = "^2.2.4"
statsmodels = "^0.14.4"
pymc = "^5.21.1"
ipython = "^8.28.0"
streamlit-option-menu = "^0.4.0"
altair = "^5.4.1"
streamlit = "^1.40.1"
abatar = {path = "../ds-abatar/dist/abatar-0.2.0-py3-none-any.whl"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

include=["/abatarapp/gallery/*"]